apiVersion: v1
kind: Secret
metadata:
  name: gitlab-tekton
  namespace: pipelines
  annotations:
    tekton.dev/git-0: https://gitlab.yourdomain.com
type: kubernetes.io/basic-auth
stringData:
  username: user
  password: password
  token: token
---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-tekton
  namespace: pipelines
  annotations:
    tekton.dev/docker-0: https://hub.yourdomain.com
stringData:
  # you can get this value from docker login command
  config.json: |
    {"auths":{"hub.yourdomain.com":{"username":"user","password":"password","auth":""}}}
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-tekton
  namespace: pipelines
type: kubernetes.io/basic-auth
stringData:
  username: user
  password: password
---